### PR TITLE
Added Incremental Saving

### LINKED ISSUE #2360: [Suggestion] "save new iteration" option in the file menu
### Detailed description of your suggestion

Save new iteration is an option commonly seen in other modeling softwares, which allows an incremental versioning of a project file.
Having this would provide a simple Quality of Life option in cases where a model or scene has a lot of "temporary" elements, which need to be removed later on, saving a new iteration would guarantee the user keeps these elements saved, but not in the final file

The usual shortcut for this is `Ctrl+Alt+S`

image

### PR DESCRIPTION
**Pull request by Azagwen**
This PR adds incremental saving, similar to what can be seen in Blender and Autodesk Maya.

https://github.com/JannisX11/blockbench/assets/30528331/49b4f6c7-6054-457f-9d94-ad2136febdd4

This would be useful to keep past versions of a given project file, without having to set up boilerplate version control tools like Git.

Would close #2360

### CODE REVIEW

**Comment by Azagwen** [comment]
At the moment this uses RegEx to isolate and add to the file name before `.bbmodel`, let me know if I should try another maybe more reliable way

**Comment by Azagwen** [comment]
an issue I found with the current ways this works; re-saving incrementally from a previous version overwrites versions above it
I could fix this by either:
- changing it so that the version nb is based on the date & hour instead of a flat integer
- checking if a file named the same exists in this spot, and saving a "bis" version if it does exist

**Comment by Azagwen** [comment]
another thing; this doesn't seem to work on the web version 🤔

**Comment by JannisX11** [comment]
I changed some things. I made the action only available when it'll actually do something useful. And I added a check for if the file already exists. I added a modification to the file name, since I think numbers are more intuitive than something like date or time in this case.

**Comment by Azagwen** [comment]
Something I've been thinking of recently to complement this:
The interation number could be written to the saved file, this would technically fix web app not incrementing, and be a reliable way beyond just the file name to tell which iteration a given file is 🤔

**Comment by Azagwen** [comment]
> I changed some things. I made the action only available when it'll actually do something useful. And I added a check for if the file already exists. I added a modification to the file name, since I think numbers are more intuitive than something like date or time in this case.

Nice! And yeah that makes sense, most other apps also only do this with a single number that gets incremented

**Comment by JannisX11** [comment]
> Something I've been thinking of recently to complement this: The interation number could be written to the saved file, this would technically fix web app not incrementing, and be a reliable way beyond just the file name to tell which iteration a given file is 🤔

I think the file name is reliable enough for remembering the number, and it gives the user a way to manually tweak it without needing a UI for it. And I'm not concerned about the web app not having it. On the web app just pressing Save Project already pretty much does the same thing, at least unless you have file saving dialogs enabled in the browser.

**Pull request merged**
