### PR TITLE
Fix texture bleeding when using anti-aliasing

### PR DESCRIPTION
**Pull request by Nestorboy**
This PR modifies the Textured and UV Preview vertex shaders to add the centroid qualifier to prevent UVs from getting extrapolated when using anti-aliasing.

I'm not certain but if mipmaps are ever introduced, I believe it could cause issues with trying to compute the mip levels. If this becomes an issue the simplest solution would be to pass non-centroid UVs and use those for the mip map derivatives and use the centroid UVs to prevent sampling texels outside of the triangles boundaries.

Should this anti-aliasing fix be tied to a setting or should it always be enabled?

centroid_comparison

### CODE REVIEW

**Comment by Nestorboy** [comment]
Hey @JannisX11, I'm mentioning you since I'm not sure if it was clear or not, but I'm looking for input on if this should be a setting or not, and if it should be on by default then. The reason it might be good to have it as a setting is in case users are exporting their models to platforms where this visual artifact might be present as well. What do you think?

**Comment by JannisX11** [comment]
That's a good point, yeah. Let's make it a setting in the preview category, and make it on by default. I don't mind if the setting requires a restart to update, similar to anti aliasing.

There are no plans for mipmaps at the moment. Id schedule this for the next feature update, it'll be nice to have this, especially for people who are rendering in Blockbench.

**Comment by Nestorboy** [comment]
It wasn't clear which branch should be the target, so feel free to change it if it should be something other than `master`

**Comment by JannisX11** [comment]
Looks great, thanks!
The branch should be `next`. I changed it.

**Pull request merged**
