### PR TITLE
Fix binary FBX export geometry & external texture exporting

### PR DESCRIPTION
**Pull request by SiboVG**
This PR is a start at fixing binary FBX exporting. With this PR, geometry exporting and texturing exporting of an external file should work. What's still broken is exporting textures created in BlockBench (and not exported externally), aka embedded textures, and exporting animations.

If someone wants to debug this further: exporting embedded textures causes Blender to throw the error "IMB_ibImageFromMemory: unknown file-format (<packed data>)". Exporting animations leaves the keyframe vales with nan values.

### CODE REVIEW

**Comment by SiboVG** [comment]
@JannisX11?

**Comment by JannisX11** [comment]
Right, sorry, I thought this was merged already. I'll try if I can find some time to test it over the weekend

**Comment by SiboVG** [comment]
> Right, sorry, I thought this was merged already. I'll try if I can find some time to test it over the weekend

Sure, no problem, thanks!

**Comment by JannisX11** [comment]
It's great that Blender is now working in general, even if not with animations or embedded textures.
I fixed a small issue here. I'll also add back the option to export with embedded textures even if a file exists, but as an export option.
Will include this PR in the 4.10 beta so that users can try it out.
Thanks!

**Comment by SiboVG** [comment]
> It's great that Blender is now working in general, even if not with animations or embedded textures. I fixed a small issue here. I'll also add back the option to export with embedded textures even if a file exists, but as an export option. Will include this PR in the 4.10 beta so that users can try it out. Thanks!

Great, thanks for the merge! Happy to have contributed :)

**Pull request merged**
