### PR TITLE
Added "Randomize Marker Color" option from #2210

### PR DESCRIPTION
**Pull request by Azagwen**
This pull adds a "random marker color" option in the outliner context menu, which will pick a random color (different from the current one) and apply it to any selected element

image

demo video:

https://github.com/JannisX11/blockbench/assets/30528331/5782180f-d332-44ef-a3be-812f3993b1eb

### CODE REVIEW

**Comment by JannisX11** [comment]
A few things to improve:
* Let's implement this as a standalone Action instead of a menu item. That way users can add it to their toolbars and assign keybindings. Actions can be added back to menus by adding their ID as a string
* Let's change the name to "Randomize Marker Colors". That way the action is more clear, and the plural clarifies that each element gets its own color
* Let's change the icon to "fa-shuffle"
* I haven't fully made up my mind about it, but it might be neat to move this action directly into the Marker Color submenu, below the other points. That way the main menu is less cluttered. But lmk your thoughts.

**Comment by Azagwen** [comment]
Will do these changes when I find the time 👍

**Comment by Azagwen** [comment]
- Made it into an action
- Changed name
- Replaced individual element code with action reference like other global actions
- Changed icon
- Code for the Group element is now the only function for this, and was moved to the action definition, as it works for all elements


https://github.com/JannisX11/blockbench/assets/30528331/8c03a830-2a7e-42ac-8c86-61599c82d373

**Comment by Azagwen** [comment]
> A few things to improve:
> 
>     * Let's implement this as a standalone Action instead of a menu item. That way users can add it to their toolbars and assign keybindings. Actions can be added back to menus by adding their ID as a string
> 
>     * Let's change the name to "Randomize Marker Colors". That way the action is more clear, and the plural clarifies that each element gets its own color
> 
>     * Let's change the icon to "fa-shuffle"
> 
>     * I haven't fully made up my mind about it, but it might be neat to move this action directly into the Marker Color submenu, below the other points. That way the main menu is less cluttered. But lmk your thoughts.

About moving this to the marker color sub-menu, I'm a little mixed myself.

Moving it there would de-clutter the context menu a little  bit, but it would also make this option less accessible (one hover away), individual marker colors being in a sub-menu makes sense UX wise, because there are 10 of them (even more with plugins) so having all of them in the context menu would  just be a massive clutter (even more with plugins, again), while the randomizer is only one option.

I'm also worried that users might miss it, or mistake it as a sort of "special" color if it's put here, given that it would be one option out of 10+. Especially if they use plugins to have more colors, causing that option to be pushed even further down and flooded by options that all behave the same from one another, and look roughly the same on the UI, if color is ignored. 🤔

**Comment by JannisX11** [comment]
Thanks, I'm happy with this!

**Pull request merged**
