### PR TITLE
Added 3D brush outline shearing and fixed triangle selection

### PR DESCRIPTION
**Pull request by Nestorboy**
• Rewrote how the brush outline is transformed by computing a custom matrix to allow for shearing.
• Added a function to mesh.js and cube.js to compute a texel to local matrix for the brush outline.
• Fixed issue where the brush uv position would get truncated before being transformed to a world position for the outline, causing it to select the wrong triangle.

blockbench_shearing

### CODE REVIEW

**Comment by Nestorboy** [comment]
@JannisX11 there's some code duplication in [mesh.js](https://github.com/JannisX11/blockbench/pull/2529/files#diff-42cf14921cfc1e6ab400da853f0221a5f04d01c1f51d788f7f39c2db57d03b5a) where I compute the brush matrix. Should it be moved to some particular location or is it fine?

**Comment by JannisX11** [comment]
Yeah, you can use a closure inside the TexelToLocalMatrix function to handle that duplicated code. Also make sure to not modify the passed `uv` parameter directly, as it may still be used for something else after calling the function. TexelToLocalMatrix should be texelToLocalMatrix, following lower camel case.

I noticed two issues when testing this feature initially:
* Brush outlines no longer work on cubes
* Higher pixel density textures no longer work, the brush outline displays too large. Texture resolutions can be higher than the UV resolution, and the brush outline should support that.

**Comment by Nestorboy** [comment]
Thank you Jannis for taking the time to test this and giving me some pointers and advice regarding my code!

I've gone over and fixed the issues you discovered, and realized that there were some other small code cleanups I could do. At this point I believe it's ready to be reviewed and merged so I'll turn it into a regular PR instead of a draft.

GitHub Desktop seems to only have let me create a new branch from `master`, so I accidentally included a commit from `master` branch which `next` doesn't have. It might not matter much, but would you mind syncing the `next` branch?

**Comment by Nestorboy** [comment]
I realized I never accounted for the soft brush not doing any form of snapping, so I've fixed that too. I also made the code behave more similarly to the previous (your) implementation where the truncation was done before the UVToLocal function

**Comment by Nestorboy** [comment]
I went ahead and rebased the branch in order to re-sync it with `next`, so you don't need to sync it with master anymore.

One feature I've been unable to test is the behaviour of the preview when working with flipbooks, but I haven't really touched that code so it should act the same. I've been unable to test flipbooks since there seems to have been a bug introduced with the dialog related changes that broke the flipbook feature.

**Pull request merged**
